### ISSUE TITLE
Still crawling for the datas

### ISSUE THREAD

**Issue by sehooh5** [SeongjinOliver/watcheap-project#29]
I've been doing crawling for CU

**Comment by SeongjinDaniel** [comment]
yeah. I finished 1+1 and 2+1 crawling now.

**Comment by SeongjinDaniel** [comment]
크롤링 끝
1. cu 1+1, 2+1 crawling
2. seveneleven address crawling

**Comment by GyuyoungEom** [comment]
1. finish emart24, ministop shopInformation crawling
