### ISSUE TITLE
Start Spring MVC

### ISSUE THREAD

**Issue by SeongjinDaniel** [SeongjinOliver/watcheap-project#41]
wow amazing!! :)

**Comment by SeongjinDaniel** [comment]
map 카테고리 관련 코드 Front-end 개발중!

**Comment by GyuyoungEom** [comment]
장바구니 관련 vo, dao, mapper 작성

**Comment by sehooh5** [comment]
테마 상품 관련 vo,dao,mapper, controller 및 view 연결 완료

**Comment by JihyeHaley** [comment]
기본적인 UI 정리 완료.
data-toggle 공부 예정
dao 작성 예정

**Comment by SeongjinDaniel** [comment]
20200519_searching기능, 카카오맵 설정 및 개발

**Comment by GyuyoungEom** [comment]
20200519_ 장바구니 jsp 수정, mapper 및 dao 작성, 전체 vo 수정, DB 입력

**Comment by sehooh5** [comment]
30300519_ 테마상품 jsp 수정

**Comment by GyuyoungEom** [comment]
20200520_ cart jsp, vo, mapper dao 수정 + memberMapper 작성

**Comment by sehooh5** [comment]
20200520_theme.jsp 수정중, 테마 추천 관련 데이터 테이블, VO 추가, 백엔드 데이터랑 연결, 중간발표 때 보여주기 식 하고 테마 추천 알고리즘은 멘토링 받고 진행할 수 있을 듯

**Comment by SeongjinDaniel** [comment]
20200520_kakaoMap 개발중(현재 위치 기반 개발완료 및 알고리즘 적용중)

**Comment by JihyeHaley** [comment]
20200520_ event.jsp, EventDAO.java, EventController.java, EventMapper.java 수정중

내일할일 ->  새로운 VO작성, SQL 구문으로 테스트하기

**Comment by sehooh5** [comment]
20200521_회원가입 관련 DAO, Controller, Mapper, Service, View 작성..아직 수정해야할 부분 많음
테마 관련 약간 수정..멘토링 후 대거 수정 예정

**Comment by sehooh5** [comment]
20200522_중간 발표. 테마 상품 뷰 수정

**Comment by sehooh5** [comment]
20200525_인스타그램 크롤링

**Comment by SeongjinDaniel** [comment]
20200602 맵 페이지 구성 데모 완료!!
